# Generated by Django 2.2.28 on 2022-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sghjt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sghjt',
            name='ghtytu',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sghjt',
            name='ugene',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
