# Generated by Django 2.2.28 on 2022-09-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20220914_0939"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sghjt",
            name="ghtytu",
        ),
    ]
