# Generated by Django 2.2.28 on 2022-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_sghjt_ghtytu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvdd123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncmdkd', models.BigIntegerField()),
            ],
        ),
    ]
